#!/bin/sh
set -e

# Check if any staged .rs files exist
if git diff --cached --name-only | grep -q '\.rs$'; then
  echo "Running cargo fmt --check..."
  cargo fmt --check
  echo "Running cargo clippy..."
  cargo clippy --workspace --all-targets -- -D warnings
fi
